### ISSUE TITLE
libADLMIDI update

### ISSUE THREAD

**Issue by sneakernets** [VolcanoMobile/adlmidi-lite#1]
The latest libADLMidi has my newest version of the DMXOPL patch. It's so much better than it was just a few days ago! Please to add when possible! 

https://github.com/sneakernets/DMXOPL/releases/tag/v2.0b

**Comment by loki666** [comment]
Ok I'll update adldata.cpp

**Comment by loki666** [comment]
just published an update of my player

**Comment by sneakernets** [comment]
Thanks, unfortunately I done did another update haha! I'm going to try take a break on it to get some other stuff done but that is easier said than done

**Comment by loki666** [comment]
greate!

I'll wait a week before publishing the update, as I don't want to hammer my users with too many frequent updates

keep up the good work

**Comment by sneakernets** [comment]
Thanks!

**Comment by sneakernets** [comment]
Good thing you waited!

https://github.com/sneakernets/DMXOPL/releases/tag/v2.1a

😜

**Comment by loki666** [comment]
hehe, you still have 7 days for the v3

**Comment by sneakernets** [comment]
hahaha I think I'm good for now, if I DO do anything else it'll be tweaking the hi-hats. But they sound good now!
