### ISSUE TITLE
You still have loop bug I already fixed in libADLMIDI

### ISSUE THREAD

**Issue by Wohlstand** [VolcanoMobile/adlmidi-lite#2]
Try to play MIDI file which has nothing inside or swap loopStart and loopEnd tags and you will get freeze!

P.S. I see you made some changes I would apply to libADLMIDI (even WOPL parser I planned to add, but you did that faster than me 😋, and the optional filters / volume increasing support). I also working on real-time API (you can see some changes I already made) which will give ability to use your existing MIDI player to pass events per step into libADLMIDI and have the support of a positioning (seek). And I also want to make the ALSA raw MIDI daemon.

EDIT: Okay, I see you have used AntiFreeze code I made to avoid freeze of empty MIDI files. But swapped loop points still not fixed

**Comment by loki666** [comment]
ok thanks, I think I'll just remove the handling of the loop points
they are not part of SMF specifications anyway...

I started back from adlmidi player (there was too many changes in your libADLMIDI I couldn't understand the logic) but I kept your API

**Comment by Wohlstand** [comment]
Anyway, I plan to push back my changes to original ADLMIDI when I will add event hooks (there are can be useful for interactive things without of hacking library itself)

**Comment by loki666** [comment]
fixed in f077d14066e591d14c97bd170c912703d884fd1c
