### ISSUE TITLE
DMX: Double-voice instruments with same operators will play as one-voice

### ISSUE THREAD

**Issue by Wohlstand** [VolcanoMobile/adlmidi-lite#3]
When both voices are same, there are will be compared as same voice and in result you will have single-voice. It's old ADLMIDI's issue I have been fixed by adding of `diff` boolean into `instdata` structure which is false by default and true on every DMX's second voice.

For example, `SynthBass 2`

**Comment by Wohlstand** [comment]
https://github.com/VolcanoMobile/adlmidi-lite/commit/b6f4c7a495be8f07dbf3430591fa8b251d1ae0d8 Doesn't fixes this issue. I just built your library from latest state and I have figured out how to compile your Go-coded example and I did test.
* [Test MIDI-file](http://wohlsoft.ru/docs/_files_for_posts/Misc/AdlMidi-SynthBassBug/039_SynthBass2-test.mid) (try to play same in real DOOM game or on any DMX-based MIDI players!)
* [How your library played it](http://wohlsoft.ru/docs/_files_for_posts/Misc/AdlMidi-SynthBassBug/doom-synthbass-bad.wav) (libadlmidi-lite + mid2wav.go)
* [How must be played](http://wohlsoft.ru/docs/_files_for_posts/Misc/AdlMidi-SynthBassBug/doom-synthbass-good.wav) (libADLMIDI + my demo tool)

I have found that accidentally when I wanted to optimize my store a bit, and I did same your fix at me - in result, it doesn't works. Then I ran your library to check is that happens at me or at you too.

**Comment by loki666** [comment]
mmm have a second look at this, but I don't see why this should works with the test on ains.flags

**Comment by Wohlstand** [comment]
In the debugger that condition passed with "Pseudo4op" flag enabled and not broken, however, single voice played.

**Comment by loki666** [comment]
there should be a bug deeper in the code...
but this code is so weird, it's like it has been obfuscated!!!

**Comment by Wohlstand** [comment]
It wasn't obfuscated, it's just a hell of templates and bad codding style. Anyway, the lot of changes I doing on libADLMIDI side is making is also it be more readable and more friendly. With recently made seekabiltiy support I did the full parsing of of raw MIDI events into the structures and queues are containing "rows" per tick with delay are listing events inside it. So, instead of real-time event parsing done in old ADLMIDI, I easily executing pre-parsed events are also more friendly readable in the debugger. This gave me ability to sort events in same row (note-offs to the top, then meta-events, then controllers and any other events in tail), future ability to fix [this hell of all ages](https://github.com/Wohlstand/libADLMIDI/issues/23) by simple delaying of note-off event by storing it into separated queue to execute a bit later, pre-validation of loop points (instead of having lots of bools to validate loop in real time), and collecting any interesting meta-data (song title, copyright, markers with tick/time position, track titles, etc., for example, lyrics and text events to provide ability implement a Karaoke player) to get them via external functions, etc.

**Comment by Wohlstand** [comment]
Okay, I finally implemented a fix of this!
Look changes I have done: https://github.com/Wohlstand/libADLMIDI/commit/3d04ebe23175c0b723d4bde8ecdecc57b31f3ad6


Because I have applied beautifier to this and I also did lot of other changes like types micro-optimizing, I'll explain my important changes to let you easier repeat them:

* In the "NoteInfo" structure:
```cpp
//Just store of integers
std::map<uint16_t /*adlchn*/, uint16_t /*ins, inde to adl[]*/ > phys;

// I have replaced with the structure that have bool which makes much easier and safer way to identify second voice
```cpp
struct Phys
{
    //! ins, inde to adl[]
    size_t  insId;
    //! Is this voice must be detunable?
    bool    pseudo4op;

    bool operator==(const Phys &oth) const
    {
        return (insId == oth.insId) && (pseudo4op == oth.pseudo4op);
    }
    bool operator!=(const Phys &oth) const
    {
        return !operator==(oth);
    }
};
typedef std::map<uint16_t, Phys> PhysMap;
std::map<uint16_t /*adlchn*/, Phys> phys;
```
* In "LocationData"
```cpp
//Just a single integer
uint16_t ins;  // a copy of that in phys[]
//Replaced with the structure
MIDIchannel::NoteInfo::Phys ins;  // a copy of that in phys[]
```

* Changed functions prototypes (but content of them is still same!!!):
```
-   long CalculateAdlChannelGoodness(unsigned c, uint16_t ins, uint16_t /*MidCh*/) const;
+   long CalculateAdlChannelGoodness(unsigned c, const MIDIchannel::NoteInfo::Phys &ins, uint16_t /*MidCh*/) const;

-   void PrepareAdlChannelForNewNote(size_t c, int ins);
+   void PrepareAdlChannelForNewNote(size_t c, const MIDIchannel::NoteInfo::Phys &ins);
```

* in MIDI player:
```cpp
//Array of integers
uint16_t i[2] = { ains.adlno1, ains.adlno2 };

//Replaced with array of Phys structures
bool pseudo_4op = ains.flags & adlinsdata::Flag_Pseudo4op;
MIDIchannel::NoteInfo::Phys voices[2] =
{
    {ains.adlno1, false},
    {ains.adlno2, pseudo_4op}
};
//then comparison of them will always false when pseudo-4-operator mode is turned on for this instrument

//Anyway, this
if(i[0] == i[1] || pseudo_4op)
//replaced with (otherwise simple comparison of structures will be false)
if(voices[0].insId == voices[1].insId || pseudo_4op)

//Then feed CalculateAdlChannelGoodness and PrepareAdlChannelForNewNote with new structures than with instrument IDs
//and "phys" array will receive those structures than instrument numbers


When using:
```cpp
//old way
opl.Patch(c, ins);
//new way
opl.Patch(c, ins.insId);

//old way
double bend = Ch[MidCh].bend + opl.GetAdlIns(ins).finetune;
//new way
double bend = Ch[MidCh].bend + opl.GetAdlIns(ins.insId).finetune;

//And finally, instead of silly instrument number comparison
if((ains.flags & adlinsdata::Flag_Pseudo4op) && ins == ains.adlno2)
//We checking is this a second voice or not
if((ains.flags & adlinsdata::Flag_Pseudo4op) && ins.pseudo4op)
```

I think, this info will be helpful to you 😉
