### ISSUE TITLE
WOPL update!

### ISSUE THREAD

**Issue by sneakernets** [VolcanoMobile/adlmidi-lite#4]
Here, don't use the release version, Some last minute stuff was added.

https://github.com/sneakernets/DMXOPL/commit/dd878d92f0d30b058c7c77929b0dac1b97cdcff4

This should do nicely. :)

**Comment by loki666** [comment]
resolved with 2289c96

**Comment by loki666** [comment]
@sneakernets awesome this patch set is incredible.
Sometimes I forget that this is FM instruments.
Why the games company couldn't come with something like this back then?
OPL3 had such a bad reputation only because they were to lazy.

**Comment by Wohlstand** [comment]
The same I can say for GS and XG standards are never used with over-OPL3 MIDI players (because of GM bank by FatMan which was for a while and was never extended except of few customizations by game creators).

**Comment by sneakernets** [comment]
I MADE ANOTHER VERSION and all that lol https://github.com/sneakernets/DMXOPL/releases/tag/v2.10
