### ISSUE TITLE
GenAdldata: Measurer is incorrect - noteOff event is wrong

### ISSUE THREAD

**Issue by Wohlstand** [VolcanoMobile/adlmidi-lite#5]
Hello!

Today, while I worked on implementing of same measurer into my OPL3 bank editor to store pre-measured lengths, after hours of research I have found that Note Off event is wrong:
```cpp
 // Keyoff the note
    for(unsigned n=0; n<n_notes; ++n)
        OPL3_WriteReg(&opl, 0xB0+n, (x[n]>>8) & 0xDF);
```
The result produces an infinitely-pressed key, therefore incorrect measurement of note release.

The fix is very easy: just multiple n to 3 in the operator address to match address of Note On event:
```cpp
 // Keyoff the note
    for(unsigned n=0; n<n_notes; ++n)
        OPL3_WriteReg(&opl, 0xB0+n*3, (x[n]>>8) & 0xDF);
```

I hope, you have understood this.

P.S. This bug still exist in original ADLMIDI, therefore, I'll report this to Bisquit.

**Comment by loki666** [comment]
good catch thanks for reporting

**Comment by Wohlstand** [comment]
Also, you will must to re-generate banks database which is totally incorrect because of this bug in the generator.
